### ISSUE TITLE
Consistency between ArborX and NimbleSM

### ISSUE THREAD

**Issue by uhetmaniuk** [NimbleSM/NimbleSM#103]
If we build NimbleSM with MPI (i.e. USE_PURE_MPI=ON) then ArborX should be built with MPI as well (i.e. -DARBORX_ENABLE_MPI=ON).
Is it possible to add a check at compile time?

**Comment by dalg24** [comment]
At compile-time you can check whether the `ARBORX_ENABLE_MPI` macro is defined.
