### ISSUE TITLE
contact manager polymorphism

### ISSUE THREAD

**Issue by nmm0** [NimbleSM/NimbleSM#11]
Currently contact manager has several macros for detecting which backend to use. This should be separated into subclasses that provide different functionality depending on the backend

**Comment by japlews** [comment]
I think I pulled these "Extras" macros out to the main() level in all cases (didn't touch BVH, obviously...). Happy to work on any needed interface changes to support dependency inversion.

**Comment by nmm0** [comment]
Closed by #21
