### ISSUE TITLE
building with standalone Kokkos

### ISSUE THREAD

**Issue by nmm0** [NimbleSM/NimbleSM#17]
```cmake
add_executable(NimbleSM_Kokkos nimble_kokkos_main.cc)
target_link_libraries(NimbleSM_Kokkos nimble::nimble Trilinos::Trilinos MPI::MPI_CXX)
```

Currently assumes that Kokkos is built as part of trilinos instead of standalone. We should check if Kokkos is used as part of Trilinos and link to Trilinos or a standalone Kokkos appropriately.

**Comment by jilpi** [comment]
We should also look at MPI::MPI_CXX, as MPI support is optional. cmake will fail if USE_PURE_MPI=OFF

**Comment by ppebay** [comment]
So even when turning that flag to **ON** it's failing too?

**Comment by jilpi** [comment]
If Trilinos is not installed (which is usually the case when using Kokkos standalone), this line will fail.
It might also fail if USE_PURE_MPI is set to OFF.

And even if we resolve those two issues, it still fails, has cmake has troubles finding Kokkos::kokkos. We're looking currently looking at it
