### ISSUE TITLE
ArborX Callbacks

### ISSUE THREAD

**Issue by nmm0** [NimbleSM/NimbleSM#233]
For the ArborX implementations, use the callback to compute contact forces in order to avoid indexing
Multiple steps
- [x]  Serial ArborX contact manager (closed issue #234, merged PR #235)
- [x]  Parallel ArborX contact manager  (already in `develop`)
- [ ]  BVH ArborX-based query (issue #236)

**Comment by uhetmaniuk** [comment]
@nmm0 @rjones-sandia 
This is already done for the ArborX parallel contact manager.
I can easily update the serial ArborX contact manager.
I will also update the BVH contact manager.
