### ISSUE TITLE
Save CMakeOutput.log for CI Actions

### ISSUE THREAD

**Issue by uhetmaniuk** [NimbleSM/NimbleSM#65]
Save the CMakeOutput.log for GitHub Actions

See
https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

**Comment by jilpi** [comment]
Feature added with commit https://github.com/NimbleSM/NimbleSM/commit/7bc9d9151a5bac79d67d34d85185cf13e15fc112

**Comment by uhetmaniuk** [comment]
This issue is not related to #54 and #69. It does not need to be combined.
Please create PR for this single issue.
