### ISSUE TITLE
Test quasistatic_tension fails with ArborX

### ISSUE THREAD

**Issue by jilpi** [NimbleSM/NimbleSM#68]
Exodiff considers the generated files are different, and outputs some errors. See log file:
[quasistatic_tension.arborx.log](https://github.com/NimbleSM/NimbleSM/files/5045115/quasistatic_tension.arborx.log)

Check line 1023-1028 of the log file:
```
exodiff: ERROR: NaN found for variable 'stress_xx' in block 1, file 2
exodiff: ERROR: NaN found for variable 'stress_xy' in block 1, file 2
exodiff: ERROR: NaN found for variable 'stress_yy' in block 1, file 2
exodiff: ERROR: NaN found for variable 'stress_yz' in block 1, file 2
exodiff: ERROR: NaN found for variable 'stress_zx' in block 1, file 2
exodiff: ERROR: NaN found for variable 'stress_zz' in block 1, file 2

```

Note: This test can pass with NimbleSM_Serial

**Comment by uhetmaniuk** [comment]
This test is not part of the Kokkos-based test list. So it was not added to the list of tests for ArborX

@rjones-sandia 
Is there a reason why this test should or should not run with Kokkos?

**Comment by rjones-sandia** [comment]
Unlike all the other tests which are explicitly integrated dynamics, the "quasistatic_tension_test" needs to solve a system of equations. I'm guessing the code author only got this working in serial. I'm a bit surprised that it won't work with Kokkos but its not a capability that I/we can afford to invest in. 

My suggestion is to preserve the capability in serial for now and deprecate testing with KOKKOS/MPI/etc.

**Comment by jilpi** [comment]
Done in current master, closing issue.
