### ISSUE TITLE
Tests uq_notch and uq_wave_in_bar fail with NimbleSM_Serial

### ISSUE THREAD

**Issue by jilpi** [NimbleSM/NimbleSM#70]
NimbleSM fails with the following error:
```
run_exodiff_test.py command: ../../cmake-build-debug/src/NimbleSM_Serial uq_notch.in

-- NimbleSM
-- version 1.1.0

terminate called after throwing an instance of 'std::logic_error'
  what():  
**** Error in Parser::ReadFile(), unknown key uq model
```

**Comment by rjones-sandia** [comment]
These tests can be deprecated for now. The UQ package is going through a major refactor and won't be part of the publicly accessible code for now.

**Comment by jilpi** [comment]
Thanks. Do you prefer to remove them totally, or move them to the WIP folder with a note?
