### ISSUE TITLE
sphere_plate_contact fails on Mac

### ISSUE THREAD

**Issue by uhetmaniuk** [NimbleSM/NimbleSM#77]
Test fails on Mac... maybe a tolerance issue?

It runs fine on Ubuntu (see Github Actions).

[sphere_plate_contact.arborx.log](https://github.com/NimbleSM/NimbleSM/files/5055236/sphere_plate_contact.arborx.log)

**Comment by rjones-sandia** [comment]
I don't have a mac build but I can loosen the tolerances so the diffs you see pass. 
If exodiff is using the usual meanings of "relative" and "absolute" tolerances I think at worse 
contact_force_x   abs diff: -2.6036309e+08 ~ -2.6036309e+08 = 1.38700e-04 (node 1394)
we are still getting about 12 digits.

**Comment by uhetmaniuk** [comment]
The following tolerances
        contact_force_x  absolute 2.000000000000e-4
        contact_force_y  absolute 2.000000000000e-5
        contact_force_z  absolute 7.000000000000e-5
make the test pass on Mac. 
We still get between 11 and 12 digits accuracy on the contact forces.
@rjones-sandia, would you be comfortable with these new tolerances in the text?

**Comment by rjones-sandia** [comment]
sure that's fine. In general 8 digits is good enough/great for dynamics IMHO
