### ISSUE TITLE
Use a consistent version of Google Test across builds / systems

### ISSUE THREAD

**Issue by jilpi** [NimbleSM/NimbleSM#88]
Google test's API evolves quickly and is often not backward compatible, causing good code to suddenly fail tests.
We should be able to specify and use a specific version of GTest framework.

3 possibilities to explore:

1. directly include a version of google test into the code base
2. use github submodule feature
3. use cmake "fetch content"

**Comment by nmm0** [comment]
Closing as we are not currently using google test, this issue is outdated
